# Generated by Django 5.2.17 on 2026-10-03 17:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_snapshot_security'),
        ('jobs', '0005_atomic_recovery_admission'),
        ('organizations', '0003_workflow_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('normal', 'Allow configured work'), ('paused', 'Pause configured work')], max_length=16)),
                ('reason', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='jobs.corecontrol')),
            ],
            options={
                'db_table': 'core_health_controls',
            },
        ),
        migrations.CreateModel(
            name='WorkflowSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot_sha256', models.CharField(max_length=64)),
                ('interval_hours', models.PositiveSmallIntegerField(choices=[(24, 'Daily'), (168, 'Weekly'), (720, 'Every 30 days')])),
                ('starts_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.assessmentsnapshot')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='jobs.workflowschedule')),
            ],
            options={
                'db_table': 'core_workflow_schedules',
            },
        ),
        migrations.CreateModel(
            name='ActionCardRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_sha256', models.CharField(max_length=64)),
                ('cards', models.JSONField()),
                ('sha256', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.assessmentsnapshot')),
            ],
            options={
                'db_table': 'core_action_card_revisions',
                'constraints': [models.UniqueConstraint(fields=('organization', 'snapshot'), name='core_card_snapshot_unique')],
            },
        ),
        migrations.CreateModel(
            name='KnownEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('services', 'Services'), ('branches', 'Branches'), ('ai_accounts', 'Ai Accounts'), ('agents', 'Agents'), ('employees', 'Employees')], max_length=16)),
                ('label', models.CharField(max_length=200)),
                ('provenance', models.CharField(default='declared', editable=False, max_length=16)),
                ('branch_profile', models.CharField(max_length=32)),
                ('as_of', models.DateTimeField()),
                ('sha256', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='jobs.knownentity')),
            ],
            options={
                'db_table': 'core_known_entities',
                'indexes': [models.Index(fields=['organization', 'category'], name='core_entity_org_category')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.CharField(max_length=64)),
                ('input_sha256', models.CharField(max_length=64)),
                ('effective_at', models.DateTimeField()),
                ('payload', models.JSONField()),
                ('sha256', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.workflowschedule')),
            ],
            options={
                'db_table': 'core_workflow_runs',
                'constraints': [models.UniqueConstraint(fields=('organization', 'operation', 'input_sha256'), name='core_run_input_unique')],
            },
        ),
    ]
