# Generated by Django 5.2.17 on 2026-10-02 20:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

SQL = r"""
ALTER TABLE integrations_quickbooksconnection OWNER TO agentledger_owner;
ALTER TABLE integrations_quickbooksattempt OWNER TO agentledger_owner;
ALTER TABLE integrations_quickbooksevent OWNER TO agentledger_owner;
REVOKE ALL ON integrations_quickbooksconnection, integrations_quickbooksattempt,
    integrations_quickbooksevent FROM PUBLIC, agentledger_app, agentledger_worker;
GRANT SELECT, INSERT, UPDATE ON integrations_quickbooksconnection,
    integrations_quickbooksattempt TO agentledger_app;
GRANT SELECT, INSERT ON integrations_quickbooksevent TO agentledger_app;
ALTER TABLE integrations_quickbooksconnection ENABLE ROW LEVEL SECURITY;
ALTER TABLE integrations_quickbooksconnection FORCE ROW LEVEL SECURITY;
ALTER TABLE integrations_quickbooksattempt ENABLE ROW LEVEL SECURITY;
ALTER TABLE integrations_quickbooksattempt FORCE ROW LEVEL SECURITY;
ALTER TABLE integrations_quickbooksevent ENABLE ROW LEVEL SECURITY;
ALTER TABLE integrations_quickbooksevent FORCE ROW LEVEL SECURITY;
CREATE POLICY owner_all ON integrations_quickbooksconnection TO agentledger_owner
    USING (true) WITH CHECK (true);
CREATE POLICY owner_all ON integrations_quickbooksattempt TO agentledger_owner
    USING (true) WITH CHECK (true);
CREATE POLICY owner_all ON integrations_quickbooksevent TO agentledger_owner
    USING (true) WITH CHECK (true);
CREATE POLICY connecting_owner ON integrations_quickbooksconnection TO agentledger_app
    USING (
        connected_by_id = NULLIF(current_setting('app.current_user_id', true), '')::uuid
        AND organization_id = NULLIF(current_setting('app.current_organization_id', true), '')::uuid
        AND environment = 'sandbox'
        AND EXISTS (SELECT 1 FROM organizations_organizationmember m
            WHERE m.organization_id = integrations_quickbooksconnection.organization_id
            AND m.user_id = integrations_quickbooksconnection.connected_by_id AND m.role = 'owner')
    );
CREATE POLICY connecting_owner ON integrations_quickbooksattempt TO agentledger_app
    USING (EXISTS (SELECT 1 FROM integrations_quickbooksconnection c
        WHERE c.id = connection_id));
CREATE POLICY connecting_owner ON integrations_quickbooksevent TO agentledger_app
    USING (EXISTS (SELECT 1 FROM integrations_quickbooksconnection c
        WHERE c.id = connection_id));
CREATE FUNCTION app_private.guard_quickbooks_identity() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
BEGIN
    IF current_user = 'agentledger_app' AND (
        NEW.organization_id IS DISTINCT FROM OLD.organization_id OR
        NEW.connected_by_id IS DISTINCT FROM OLD.connected_by_id OR
        NEW.environment IS DISTINCT FROM OLD.environment
    ) THEN
        RAISE EXCEPTION 'Connection identity is immutable' USING ERRCODE = '42501';
    END IF;
    RETURN NEW;
END;
$$;
ALTER FUNCTION app_private.guard_quickbooks_identity() OWNER TO agentledger_owner;
REVOKE ALL ON FUNCTION app_private.guard_quickbooks_identity() FROM PUBLIC;
CREATE TRIGGER quickbooks_identity_immutable BEFORE UPDATE
ON integrations_quickbooksconnection FOR EACH ROW
EXECUTE FUNCTION app_private.guard_quickbooks_identity();
"""
REVERSE = r"""
REVOKE ALL ON integrations_quickbooksconnection, integrations_quickbooksattempt,
    integrations_quickbooksevent FROM agentledger_app, agentledger_worker;
DROP TRIGGER quickbooks_identity_immutable ON integrations_quickbooksconnection;
DROP FUNCTION app_private.guard_quickbooks_identity();
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0002_database_security"),
        ("organizations", "0002_public_onboarding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickBooksConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "environment",
                    models.CharField(default="sandbox", editable=False, max_length=16),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disconnected", "Disconnected"),
                            ("connected", "Connected"),
                            ("reconnect", "Reconnect required"),
                            ("revoking", "Disconnect pending"),
                        ],
                        default="disconnected",
                        max_length=16,
                    ),
                ),
                ("encrypted_credentials", models.TextField(blank=True)),
                ("access_expires_at", models.DateTimeField(null=True)),
                ("refresh_expires_at", models.DateTimeField(null=True)),
                ("generation", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuickBooksAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("state_hash", models.CharField(max_length=64, unique=True)),
                ("session_hash", models.CharField(max_length=64)),
                ("generation", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integrations.quickbooksconnection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuickBooksEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="integrations.quickbooksconnection",
                    ),
                ),
            ],
        ),
        migrations.RunSQL(SQL, REVERSE),
    ]
