# Generated by Django 5.2.17 on 2026-10-03 11:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

SQL = """
ALTER TABLE integrations_providerconnection OWNER TO agentledger_owner;
ALTER TABLE integrations_providerattempt OWNER TO agentledger_owner;
ALTER TABLE integrations_providerevent OWNER TO agentledger_owner;
REVOKE ALL ON integrations_providerconnection, integrations_providerattempt,
    integrations_providerevent FROM PUBLIC, agentledger_app, agentledger_worker;
GRANT SELECT, INSERT, UPDATE ON integrations_providerconnection,
    integrations_providerattempt TO agentledger_app;
GRANT SELECT, INSERT ON integrations_providerevent TO agentledger_app;
ALTER TABLE integrations_providerconnection ENABLE ROW LEVEL SECURITY;
ALTER TABLE integrations_providerconnection FORCE ROW LEVEL SECURITY;
ALTER TABLE integrations_providerattempt ENABLE ROW LEVEL SECURITY;
ALTER TABLE integrations_providerattempt FORCE ROW LEVEL SECURITY;
ALTER TABLE integrations_providerevent ENABLE ROW LEVEL SECURITY;
ALTER TABLE integrations_providerevent FORCE ROW LEVEL SECURITY;
CREATE POLICY owner_all ON integrations_providerconnection TO agentledger_owner
    USING (true) WITH CHECK (true);
CREATE POLICY owner_all ON integrations_providerattempt TO agentledger_owner
    USING (true) WITH CHECK (true);
CREATE POLICY owner_all ON integrations_providerevent TO agentledger_owner
    USING (true) WITH CHECK (true);
CREATE POLICY connecting_owner ON integrations_providerconnection TO agentledger_app
    USING (
        connected_by_id = NULLIF(current_setting('app.current_user_id', true), '')::uuid
        AND organization_id = NULLIF(current_setting('app.current_organization_id', true), '')::uuid
        AND environment = 'owner_preview' AND provider IN ('microsoft', 'xero')
        AND EXISTS (SELECT 1 FROM organizations_organizationmember m
            WHERE m.organization_id = integrations_providerconnection.organization_id
            AND m.user_id = integrations_providerconnection.connected_by_id AND m.role = 'owner')
    );
CREATE POLICY connecting_owner ON integrations_providerattempt TO agentledger_app
    USING (EXISTS (SELECT 1 FROM integrations_providerconnection c
        WHERE c.id = connection_id));
CREATE POLICY connecting_owner ON integrations_providerevent TO agentledger_app
    USING (EXISTS (SELECT 1 FROM integrations_providerconnection c
        WHERE c.id = connection_id));
CREATE FUNCTION app_private.guard_provider_identity() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
BEGIN
    IF current_user = 'agentledger_app' AND (
        NEW.id IS DISTINCT FROM OLD.id OR
        NEW.provider IS DISTINCT FROM OLD.provider OR
        NEW.organization_id IS DISTINCT FROM OLD.organization_id OR
        NEW.connected_by_id IS DISTINCT FROM OLD.connected_by_id OR
        NEW.environment IS DISTINCT FROM OLD.environment
    ) THEN
        RAISE EXCEPTION 'Connection identity is immutable' USING ERRCODE = '42501';
    END IF;
    RETURN NEW;
END;
$$;
ALTER FUNCTION app_private.guard_provider_identity() OWNER TO agentledger_owner;
REVOKE ALL ON FUNCTION app_private.guard_provider_identity() FROM PUBLIC;
CREATE TRIGGER provider_identity_immutable BEFORE UPDATE
ON integrations_providerconnection FOR EACH ROW
EXECUTE FUNCTION app_private.guard_provider_identity();

CREATE FUNCTION app_private.guard_provider_attempt_identity() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
BEGIN
    IF current_user = 'agentledger_app' AND (
        NEW.id IS DISTINCT FROM OLD.id OR
        NEW.connection_id IS DISTINCT FROM OLD.connection_id OR
        NEW.state_hash IS DISTINCT FROM OLD.state_hash OR
        NEW.session_hash IS DISTINCT FROM OLD.session_hash OR
        NEW.generation IS DISTINCT FROM OLD.generation OR
        NEW.expires_at IS DISTINCT FROM OLD.expires_at OR
        OLD.consumed_at IS NOT NULL
    ) THEN
        RAISE EXCEPTION 'Attempt identity or consumed state is immutable' USING ERRCODE = '42501';
    END IF;
    RETURN NEW;
END;
$$;
ALTER FUNCTION app_private.guard_provider_attempt_identity() OWNER TO agentledger_owner;
REVOKE ALL ON FUNCTION app_private.guard_provider_attempt_identity() FROM PUBLIC;
CREATE TRIGGER provider_attempt_identity_immutable BEFORE UPDATE
ON integrations_providerattempt FOR EACH ROW
EXECUTE FUNCTION app_private.guard_provider_attempt_identity();
"""
REVERSE = """
REVOKE ALL ON integrations_providerconnection, integrations_providerattempt,
    integrations_providerevent FROM agentledger_app, agentledger_worker;
DROP TRIGGER provider_identity_immutable ON integrations_providerconnection;
DROP FUNCTION app_private.guard_provider_identity();

DROP TRIGGER provider_attempt_identity_immutable ON integrations_providerattempt;
DROP FUNCTION app_private.guard_provider_attempt_identity();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
        ("organizations", "0002_public_onboarding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("microsoft", "Microsoft"), ("xero", "Xero")],
                        max_length=16,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        default="owner_preview", editable=False, max_length=16
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disconnected", "Disconnected"),
                            ("connected", "Connected"),
                            ("reconnect", "Reconnect required"),
                            ("revoking", "Disconnect pending"),
                        ],
                        default="disconnected",
                        max_length=16,
                    ),
                ),
                ("encrypted_credentials", models.TextField(blank=True)),
                ("access_expires_at", models.DateTimeField(null=True)),
                ("generation", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("state_hash", models.CharField(max_length=64, unique=True)),
                ("session_hash", models.CharField(max_length=64)),
                ("generation", models.PositiveIntegerField()),
                ("encrypted_verifier", models.TextField()),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integrations.providerconnection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="integrations.providerconnection",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="providerconnection",
            constraint=models.UniqueConstraint(
                fields=("organization", "provider"), name="one_provider_per_workspace"
            ),
        ),
        migrations.RunSQL(SQL, REVERSE),
    ]
